.MODEL SMALL
.STACK 100H
.DATA
PROMPTMSG DB 'PLEASE ENTER A NUMBER [1..100]',13,10,'$'
GREATERMSG DB 'YOU HAVE ENTERED A GREATER NUMBER', 13, 10, '$'
LESSMSG DB 'YOU HAVE ENTERED A LESSER NUMBER', 13 , 10, '$'
CORRECTMSG DB 'YOU HAVE HIT THE RIGHT NUMBER', 13, 10, '$'
NUMBR DW 27
.CODE
.STARTUP
   MOV  AX,@DATA
   MOV  DS,AX                   
   LEA DX, PROMPTMSG
   MOV  AH,9    
   INT  21H                     
   MOV AH, 0AH
   INT 21H
   MOV AH, 9
   INT 21H
   MOV BX, NUMBR
   CMP AX, BX
   JB LESSER
   JA GREATER
CORRECT:
   MOV DX, OFFSET CORRECTMSG
   MOV AH, 09H
   INT 21H
   JMP ENDEXE
GREATER:
   MOV DX, OFFSET GREATERMSG
   MOV AH, 09H
   INT 21H
   JMP ENDEXE
LESSER:
   MOV DX, OFFSET LESSMSG
   MOV AH, 09H
   INT 21H
ENDEXE:
   MOV  AH,4CH                 
   INT  21H                    
   END
