MOV AL,6H
MOV BL,5H

INC AX; INCREASES BY 1 BIT
INC BYTE PTR[AL]; INCREASES BY 1 TO BYTE CONTENTS OF DATA SEGMENT MEMORY LOCATION, BX 
INC WORD PTR[SI]; INCREASES BY 1 TO WORD CONTENTS OF DATA SEGMENT MEMORY LOCATION, SI
INC DWORD PTR[ECX]; INCREASES BY 1 TO DOUBLE CONTENTS OF DATA SEGMENT MEMORY LOCATION, ECX
INC DATA1;INCREASE CONTENTS OF DATA SEGMENT MEMORY LOCATION, DATA1

ADD AX, BX; ADDITION
SUB AX, BX; SUBSTRACTION
MUL BX; MULTIPICATION
DIV AX; DIVISION   


DEC AX; DECREASES BY 1 BIT
DEC BYTE PTR[AX]; DECREASES BY 1 TO BYTE CONTENTS OF DATA SEGMENT MEMORY LOCATION, BX 
DEC WORD PTR[SI]; DECREASES BY 1 TO WORD CONTENTS OF DATA SEGMENT MEMORY LOCATION, SI
DEC DWORD PTR[SECX]; DECREASES BY 1 TO DOUBLE CONTENTS OF DATA SEGMENT MEMORY LOCATION, ECX
DEC DATA1; DECREASE CONTENTS OF DATA SEGMENT MEMORY LOCATION, DATA1   

ADC AL,BL; ADDITION WITH CARRY WHERE AX=AX+BX+CARRY   

CBW; CONVERT BYTE INTO WORDS    

DAA; DECIMAL ADJUST AFTER ADDITION

XCHG AL,BL; EXCHANGE CONTENTS  

CMP AL, BL; CHANGES FLAG BITS NOT DESTINATION OPERAND, COMPARES LIKE IF LOOP

TEST AL, 4; ALMOST AND OPEARATION

NOT AL;
AND AL, BL;
OR AL, BL;  

LEA SI, [AL+BL]; MOVES ADDRESS OF THE SOUTCE TO LOCATION

MOV CL,1

SHL AL,CL; SHIFT LOGICAL LEFT, EQUIVALENT MULTIPLE OF 2^n
SHR AL,CL; SHIFT LOGICAL RIGHT, EQUIVALENT DIVISION OF 2^n
SAL AL,CL; SHIFT ARITHMATIC LEFT
SAR AL,CL; SHIFT ARITHMATIC RIGHT   

ROL AL, CL;
ROR AL, CL;
RCR AL, CL;
RCL AL, CL;

PUSH AL;
POP AL;
